title: motor-robot-buggy-scratch-2
hero_image: images/banner.png
description: motor-robot-buggy-scratch-2 description
version: 4
listed: false
copyedit: false
last_tested: "2020-02-25"
steps:
  - title: Introduction
  - title: Setting up your motors
  - title: Testing the motors with Scratch
  - title: What are motors for?
  - title: "Challenge: Adapting your motor project"
    challenge: true
  - title: Reaction game
  - title: Making a robot buggy
  - title: Remote Scratch using Real VNC
  - title: Scratch visual remote
  - title: Alternative visual remote
  - title: Scratch keyboard remote
  - title: Programmed maze journeys
  - title: What next?