title: motor-robot-buggy-scratch-2
hero_image: images/banner.png
description: motor-robot-buggy-scratch-2 description
version: 4
listed: false
copyedit: false
last_tested: "2020-02-25"
steps:
  - title: Introduction
  - title: Step title
  - title: What next?
